; Listing generated by Microsoft (R) Optimizing Compiler Version 12.00.8943.0 

	TITLE	D:\Kip\AsmBook4\Examples\HLL_Linking\VisualCPP\FindArray\findArr.cpp
	.386P
include listing.inc
if @Version gt 510
.model FLAT
else
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
_DATA	SEGMENT DWORD USE32 PUBLIC 'DATA'
_DATA	ENDS
CONST	SEGMENT DWORD USE32 PUBLIC 'CONST'
CONST	ENDS
_BSS	SEGMENT DWORD USE32 PUBLIC 'BSS'
_BSS	ENDS
$$SYMBOLS	SEGMENT BYTE USE32 'DEBSYM'
$$SYMBOLS	ENDS
$$TYPES	SEGMENT BYTE USE32 'DEBTYP'
$$TYPES	ENDS
_TLS	SEGMENT DWORD USE32 PUBLIC 'TLS'
_TLS	ENDS
;	COMDAT _FindArray2
_TEXT	SEGMENT PARA USE32 PUBLIC 'CODE'
_TEXT	ENDS
FLAT	GROUP _DATA, CONST, _BSS
	ASSUME	CS: FLAT, DS: FLAT, SS: FLAT
endif

INCLUDELIB LIBCD
INCLUDELIB OLDNAMES

PUBLIC	_FindArray2
; Function compile flags: /Odt /ZI
; File d:\kip\asmbook4\examples\hll_linking\visualcpp\findarray\findarr.cpp
;	COMDAT _FindArray2
_TEXT	SEGMENT
_searchVal$ = 8
_array$ = 12
_count$ = 16
_i$ = -4
_FindArray2 PROC NEAR					; COMDAT

; 8    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi

; 9    :   for(int i = 0; i < count; i++)

	mov	DWORD PTR _i$[ebp], 0
	jmp	SHORT $L280
$L281:
	mov	eax, DWORD PTR _i$[ebp]
	add	eax, 1
	mov	DWORD PTR _i$[ebp], eax
$L280:
	mov	eax, DWORD PTR _i$[ebp]
	cmp	eax, DWORD PTR _count$[ebp]
	jge	SHORT $L282

; 10   :     if( searchVal == array[i] )

	mov	eax, DWORD PTR _i$[ebp]
	mov	ecx, DWORD PTR _array$[ebp]
	mov	edx, DWORD PTR _searchVal$[ebp]
	cmp	edx, DWORD PTR [ecx+eax*4]
	jne	SHORT $L283

; 11   :       return true;

	mov	al, 1
	jmp	SHORT $L278
$L283:

; 12   : 
; 13   :   return false;

	jmp	SHORT $L281
$L282:
	xor	al, al
$L278:

; 14   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_FindArray2 ENDP
_TEXT	ENDS
END
